services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "11451:11451"
    environment:
      - RUST_LOG=info
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=11451
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "11452:80"
    depends_on:
      - backend
    restart: unless-stopped
