[build]
builder = "nixpacks"
buildCommand = "cd backend && cargo build --release"

[deploy]
startCommand = "cd backend && ./target/release/death-oji-backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
timeout = 100
interval = 30
